### ISSUE TITLE
Validate transmission losses - PyPSA-Earth

### ISSUE THREAD

**Issue by SermishaNarayana** [open-energy-transition/geothermal-modelling#15]

**Comment by SermishaNarayana** [comment]
PyPSA-Earth is a lossless power model. Hence transmission losses are essentially 0

**Comment by ekatef** [comment]
Hey @SermishaNarayana, not sure what you mean as "lossless", but I think it's better to ask @davide-f who has expert knowledge in power system modeling

**Comment by SermishaNarayana** [comment]
Hey @ekatef 
What I meant by lossless is that - transmission losses of the transmission network are not accounted for in the modelling. the balance equation is :
 electricity generation = electricity demand + transmission losses
 Since transmission losses = 0, electricity generation = electricity demand

**Comment by ekatef** [comment]
> Hey @ekatef What I meant by lossless is that - transmission losses of the transmission network are not accounted for in the modelling. the balance equation is : electricity generation = electricity demand + transmission losses Since transmission losses = 0, electricity generation = electricity demand

Thanks a lot for the answer @SermishaNarayana! Great to have an opportunity to discuss the foundation of the model. To me, it feels like PyPSA documentation may need some improvements 😄 

My understanding is that we should account for the losses in a kind-of indirect way as we account for electric resistance of the lines and solve Kirchhoff equations. A condition `generation = electricity demand` is assumed for a point located at the end of the line, while calculation of the power available at this point should still account for resistive and reactive losses in the line which has transported electrical energy to the demand.

Does it sound reasonable for you?

**Comment by SermishaNarayana** [comment]
> > Hey @ekatef What I meant by lossless is that - transmission losses of the transmission network are not accounted for in the modelling. the balance equation is : electricity generation = electricity demand + transmission losses Since transmission losses = 0, electricity generation = electricity demand
> 
> Thanks a lot for the answer @SermishaNarayana! Great to have an opportunity to discuss the foundation of the model. To me, it feels like PyPSA documentation may need some improvements 😄
> 
> My understanding is that we should account for the losses in a kind-of indirect way as we account for electric resistance of the lines and solve Kirchhoff equations. A condition `generation = electricity demand` is assumed for a point located at the end of the line, while calculation of the power available at this point should still account for resistive and reactive losses in the line which has transported electrical energy to the demand.
> 
> Does it sound reasonable for you?

Indeed @ekatef. I totally agree with you. Even at end of line, `generation = electricity demand` may not be completely true. Losses may occur in terms of self-consumption of the generators.
