### ISSUE TITLE
Running the model without errors - PyPSA-Earth (using PyPSA-Earth input data)

### ISSUE THREAD

**Issue by SermishaNarayana** [open-energy-transition/geothermal-modelling#19]
Execute the following command from the pypsa-earth directory in the submodule workflow:
**snakemake -call solve_all_networks --cores all --printshellcmds --configfile <config_file_path>**

-j 1 : number of cores 
--printshellcmds : flag to print shell commands
config_file_path : relative to pypsa-earth folder
-n : flag for a dry run to check number of rules to be executed in the workflow

**Comment by SermishaNarayana** [comment]
Notebook to analyse the results

[Analysis_PE.ipynb.zip](https://github.com/user-attachments/files/16244280/Analysis_PE.ipynb.zip)

**Comment by finozzifa** [comment]
### Recap from July 16th 2024

- Activities:

1. Run the model with 
 `extendable_carriers:
    Generator: [OCGT]
    StorageUnit: []  # battery, H2
    Store: [battery, H2]
    Link: []  # H2 pipeline`

- Charts and notebooks: [data_validation_20240716.zip](https://github.com/user-attachments/files/16246565/data_validation_20240716.zip)

**Comment by finozzifa** [comment]
### Recap from July 16th 2024 (morning CET)

**Activities**

Run the model with `extendable_carriers: Generator: [OCGT]`, using `pypsa-earth/networks/US_2021/elec_s_10_ec_lcopt_Co2L-24H.nc` where

```
n.generators.loc[network_to_modify.generators.carrier == "solar", "p_nom_extendable"] = False
n.generators.loc[network_to_modify.generators.carrier == "onwind", "p_nom_extendable"] = False
n.generators.loc[network_to_modify.generators.carrier == "offwind-ac", "p_nom_extendable"] = False
n.generators.loc[network_to_modify.generators.carrier == "offwind-dc", "p_nom_extendable"] = False
```

and where we set `s_max_pu: 1.0`

The results, charts and networks are available at [data_validation_20240717.zip](https://github.com/user-attachments/files/16262052/data_validation_20240717.zip)

**Comment by finozzifa** [comment]
### Recap from July 17th 2024 (afternoon CET)

**Activities**

Run the model with `extendable_carriers: Generator: [OCGT]`, using `pypsa-earth/networks/US_2021/elec_s_10_ec_lcopt_Co2L-24H.nc` where

```
n.generators.loc[network_to_modify.generators.carrier == "solar", "p_nom_extendable"] = False
n.generators.loc[network_to_modify.generators.carrier == "onwind", "p_nom_extendable"] = False
n.generators.loc[network_to_modify.generators.carrier == "offwind-ac", "p_nom_extendable"] = False
n.generators.loc[network_to_modify.generators.carrier == "offwind-dc", "p_nom_extendable"] = False
```

with `s_max_pu: 0.7`, with 

```
co2limit: 1.4728e+9
co2base: 226.86e+6
```

and with the one year cutout for the [northern emisphere](https://drive.google.com/file/d/1Ew7rQT0VNBqJW1AUrOrOP2IJKSJS7Uoy/view).

The results, charts and networks are available at [data_validation_20240717_afternoon.zip](https://github.com/user-attachments/files/16267762/data_validation_20240717_afternoon.zip)

The solved network is available at [elec_s_10_ec_lcopt_Co2L-24H.nc.zip](https://github.com/user-attachments/files/16267782/elec_s_10_ec_lcopt_Co2L-24H.nc.zip)

**Comment by finozzifa** [comment]
[data_validation_20240718_morning.zip](https://github.com/user-attachments/files/16281946/data_validation_20240718_morning.zip)

**Comment by danielelerede-oet** [comment]
Here you can fnd the updated validation notebook with the comparison between EIA and BE data too. It also contains the 4 files used in the notebook and I modified the file collection rows so that now the notebook is not dependent anymore on the local path on Fabrizio's PC.

[data_validation_20240718_afternoon.zip](https://github.com/user-attachments/files/16285625/data_validation_20240718_afternoon.zip)

**Comment by SermishaNarayana** [comment]
The files that were obtained after executing the "build_powerplants" and "clean_osm_data" rule is available here. These are the powerplant data that is fetched from powerplant matching website and used in the network. 

Re-executing the build_powerplants rule may be required if custom_powerplants is set to True (in which case the clean_osm_data rule may need to be uncommented in the Snakefile)

[powerplants_osm2pm.csv](https://github.com/user-attachments/files/16313874/powerplants_osm2pm.csv)
[powerplants.csv](https://github.com/user-attachments/files/16313875/powerplants.csv)

As a summary to run the model with the custom_powerplants.csv file
in the config file,
Set estimate_renewable_capacities to 'false'
Set custom_powerplants to 'true'
If required uncomment 'clean_osm_data' rule in snakemake workflow
