### ISSUE TITLE
Integrate Breakthrough Energy Venture data into PyPSA-Earth and run the model

### ISSUE THREAD

**Issue by finozzifa** [open-energy-transition/geothermal-modelling#26]
### Config and Snakefile changes

- [ ] Switch off fetch of renewable capacities from IRENA dataset by setting in `Config/config.usa_PE.yaml`
```
estimate_renewable_capacities:
    stats: "False" 
```
- [ ] Un-comment clean_osm_data in `workflow/pypsa-earth/Snakefile`
- [ ] Take the plants_merged.csv dataset from PyPSA-US, renamed it to custom_powerplants.csv and place it in `workflow/pypsa-earth/data folder`
- [ ] Take a custom powerplants file. To do it, modify the following key in `Config/config.usa_PE.yaml`
```
custom_powerplants: "replace"  #  "false" use only powerplantmatching (ppm) data, "merge" combines ppm and custom powerplants, "replace" use only custom powerplants
```
- [ ] Further modify the `Config/config.usa_PE.yaml` file such that
    - `extendable_carriers: Generator: [ ]`
    - `co2limit: 1.4728e+9` and `co2base: 226.86e+6`
    - `load_shedding: false`

**Files**
[plants_merged.csv](https://github.com/user-attachments/files/16330670/plants_merged.csv)
[custom_powerplants.csv](https://github.com/user-attachments/files/16330678/custom_powerplants.csv)

### Model execution steps

- [x] Check what cutout you are using, whether the one week cutout or the one provided at [northern emisphere](https://drive.google.com/file/d/1Ew7rQT0VNBqJW1AUrOrOP2IJKSJS7Uoy/view)

- [x] build the powerplant file with `snakemake -call build_powerplants --cores all --printshellcmds --configfile ../../Config/config.usa_PE.yaml`
- [x] run the model with `snakemake -call solve_all_networks --cores all --printshellcmds --configfile ../../Config/config.usa_PE.yaml`
- [x] using the notebook `modify_network.ipynb` modify the network `pypsa-earth/networks/US_2021/elec_s_10_ec_lcopt_Co2L-24H.nc` so that
```
n.generators.loc[:,  "p_nom_extendable"] = False
```
- [x] run the model with `snakemake -call solve_all_networks --cores all --printshellcmds --configfile ../../Config/config.usa_PE.yaml`

**Files**
[data_validation.zip](https://github.com/user-attachments/files/16333841/data_validation.zip)

**Comment by SermishaNarayana** [comment]
Two part data integration

- [ ] Integration of installed capacity data from BEV
- [ ] Integration of demand profile from BEV

**Comment by finozzifa** [comment]
To modify demand_profile

- [ ] modify the data/ssp2-2.6/2030/era5_2013/NorthAmerica.csv including the demand profile from BEV
- [ ] execute `snakemake -call build_demand_profiles --cores all --printshellcmds --configfile config.yaml`

**Comment by danielelerede-oet** [comment]
The difference between conventional (dam and ROR) and PHS in hydroelectric capacity (not peesent in the BEV dataset) is now envisaged in custom_powerplants.

1) Check on the powerplantmatching dataset (correspondence between ppm and BEV found for just 5 plants and several mistakes spotted - e.g. coal/gas power plants mistaken for hydro power plants)
2) Classification of hydro power plants and double check performed based on:
https://clui.org/projects/offstream/pumped-storage-facilities-usa (specifically for PHS)
https://en.wikipedia.org/wiki/List_of_run-of-the-river_hydroelectric_power_stations (specifically for ROR plants)
https://www.certrec.com/blog/certrec-market-research/top-ten-largest-hydro-plants-in-the-united-states/
https://hydroreform.org/on-your-river/
3) Final check on the validation of installed capacity (PyPSA-Earth VS EIA)

**Comment by finozzifa** [comment]
Progress was made in including the BEV demand profile into PyPSA-Earth. The steps were:

- [ ] download the BEV reference data from this [USATestSystem.zip](https://zenodo.org/records/4538590/files/USATestSystem.zip?download=1)]. In particular we used the data set USATestSystem/base_grid/demand.csv

**Comment by danielelerede-oet** [comment]
Comparison of electricity generation results after the updates of costs.csv:
![Image](https://github.com/user-attachments/assets/f60c4e38-7081-41f1-a816-ff441997ac7e)

Corresponding to the merit order below:


![Image](https://github.com/user-attachments/assets/c3ae144a-76e8-4781-b8de-ba199257f8d3)
