### ISSUE TITLE
Check  merit-order

### ISSUE THREAD

**Issue by finozzifa** [open-energy-transition/geothermal-modelling#27]
- [ ] In the `Config/config.usa_PE.yaml` use `retrieve_cost_data: true`. This downloads the cost data
- [ ] Copy the downloaded cost data to `data/costs.csv`
- [ ] In the `Config/config.usa_PE.yaml` use `retrieve_cost_data: false`. This makes sure that the model uses `data/costs.csv`
- [ ] Modify `data/costs.csv` as needed

**Comment by finozzifa** [comment]
Comparison of the marginal costs (not actual values though): available [here](https://www.wri.org/technical-perspectives/insider-demystifying-us-electricity-markets-and-their-role-clean-energy-expansion)

**Comment by SermishaNarayana** [comment]
Some costs data from EIA for 2021 are available [here](https://www.eia.gov/outlooks/aeo/assumptions/pdf/table_8.2.pdf) (Looks promising)

**Comment by danielelerede-oet** [comment]
File costs.csv updated to integrate revised Investment, fixed and variable O&M, and fuel costs costs for the USA. Calculations available in
[costs_calculations.ods](https://github.com/user-attachments/files/16443534/costs_calculations.ods)
New costs.csv file to upload in the workflow (remember to set retrieve_costs to 'False' in the config file):
[costs.csv](https://github.com/user-attachments/files/16443544/costs.csv)

Difference in the marginal costs computed by PyPSA-Earth:
![Image](https://github.com/user-attachments/assets/820ba061-cf5b-4540-93a6-7d39a09ef577)

**Comment by SermishaNarayana** [comment]
[Coal usage facts](https://www.energy.gov/sites/default/files/2024-04/Coal%20Factsheet_4.18.24.pdf) - bituminous, subbituminous and lignite are commonly used grades of coal in the US 

[EIA annual coal report ](https://www.eia.gov/coal/annual/)

[EIA coal prices](https://www.eia.gov/coal/annual/pdf/tableES4.pdf)

The data from these sources was used to re-calculate coal fuel price in the model
